title: SemioMaths
description: MSCA Project
show_downloads: true
google_analytics:
# theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  home: ./
  about: ./p.about.html
  semiolog: ./p.semiolog.html
  publications: ./p.publications.html
  talks: ./p.talks.html
  teaching: ./p.teaching.html
  contact: ./p.contact.html

img:
  photo: ./assets/img/SemioMaths.pdf
  background: ./assets/img/heatmap.png

# pdf:
#   2023s: ./pdf.test.html